version: 2
updates:

  - package-ecosystem: docker
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"

  - package-ecosystem: pip
    commit-message:
      prefix: chore
    directory: /tests
    schedule:
      interval: monthly
      day: saturday
    groups:
      python-test-dependencies:
        patterns:
          - "*"
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"

  - package-ecosystem: gitsubmodule
    commit-message:
      prefix: chore
    directory: /
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"

  - package-ecosystem: npm
    commit-message:
      prefix: chore
    directory: /scripts/linkbot/
    schedule:
      interval: monthly
      day: saturday
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
